### ISSUE TITLE
Action remove my commit history

### ISSUE THREAD

**Issue by pszafer** [KTibow/ha-blueprint#17]
Hi,

I used your action in my integration https://github.com/bosch-thermostat/home-assistant-bosch-custom-component
```
name: "Validation And Formatting"
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: actions/setup-python@v2
        name: Setup Python
        with:
          python-version: '3.8.x'
      - uses: actions/cache@v2
        name: Cache
        with:
          path: |
            ~/.cache/pip
          key: custom-component-ci
      - uses: hacs/action@main
        with:
          category: integration
          ignore: wheels
      - uses: KTibow/ha-blueprint@stable
        name: CI
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

and since February/March it removes my commits history...
You can see here https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/commits/master that first commit is in March and I maintain this integration for 2-3 years.
For now I removed thiat action.
